import type { Product } from "@/lib/types";

export const demoProducts: Product[] = [
  {
    id: "smart-watch-pro",
    title: "Smart Watch Pro X9",
    description: "ساعة ذكية مقاومة للماء مع تتبع صحي، بطارية طويلة، وتنبيهات فورية مناسبة للعمل والرياضة.",
    price: 149,
    originalPrice: 219,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80",
    category: "إلكترونيات",
    merchant: "ArabClicks Demo",
    storeName: "Gulf Tech Store",
    merchantName: "Gulf Tech Trading LLC",
    storeRating: 4.7,
    merchantCustomerRating: 4.8,
    merchantReviewCount: 1840,
    merchantReliabilityScore: 96,
    merchantReliabilityLabel: "موثوق جدًا",
    merchantResponseRate: 97,
    merchantVerifiedSince: "2021",
    shippingInfo: "شحن خلال 2-4 أيام",
    returnPolicy: "إرجاع خلال 14 يومًا حسب سياسة المتجر",
    trustScore: 94,
    aiExplanation: "هذا العرض مناسب لمن يريد ساعة ذكية بسعر أقل من المتوسط وتقييم مرتفع. السعر الحالي أقل من السعر السابق بنسبة واضحة والطلب عليه مرتفع خلال آخر ساعة.",
    pros: ["سعر أقل من المتوسط", "تقييم متجر مرتفع", "بطارية طويلة"],
    cons: ["الألوان المتاحة محدودة"],
    comparisonReason: "أفضل توازن بين السعر، التقييم، وسرعة الشحن.",
    affiliateUrl: "https://example.com/checkout/smart-watch-pro?aff_id=demo",
    rating: 4.8,
    soldLastHour: 43,
    discountPercent: 31,
    availability: "LimitedAvailability",
  },
  {
    id: "wireless-earbuds",
    title: "Noise Canceling Wireless Earbuds",
    description: "سماعات لاسلكية بعزل ضوضاء نشط وصوت عميق مناسبة للسفر والعمل والمكالمات اليومية.",
    price: 79,
    originalPrice: 104,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=900&q=80",
    category: "صوتيات",
    merchant: "Admitad Demo",
    storeName: "Audio Market",
    merchantName: "Audio Market Global",
    storeRating: 4.6,
    merchantCustomerRating: 4.6,
    merchantReviewCount: 1265,
    merchantReliabilityScore: 92,
    merchantReliabilityLabel: "موثوق",
    merchantResponseRate: 94,
    merchantVerifiedSince: "2020",
    shippingInfo: "شحن سريع متاح",
    returnPolicy: "استبدال عند وجود عيب مصنعي",
    trustScore: 91,
    aiExplanation: "الخيار قوي للعميل الذي يبحث عن عزل ضوضاء بسعر عملي. التقييم جيد والسعر أقل من عروض مشابهة في نفس الفئة.",
    pros: ["عزل ضوضاء نشط", "سعر منافس", "مناسبة للمكالمات"],
    cons: ["لا تدعم كل ميزات الأجهزة القديمة"],
    comparisonReason: "أرخص من بدائل صوتية قريبة مع تقييم مستقر.",
    affiliateUrl: "https://example.com/checkout/wireless-earbuds?aff_id=demo",
    rating: 4.7,
    soldLastHour: 28,
    discountPercent: 24,
    availability: "InStock",
  },
  {
    id: "air-fryer-family",
    title: "Family Air Fryer 7L",
    description: "قلاية هوائية كبيرة للعائلة ببرامج طبخ ذكية وسلة سهلة التنظيف وسعة مناسبة للاستخدام اليومي.",
    price: 119,
    originalPrice: 145,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1626200921347-172f68f4b988?auto=format&fit=crop&w=900&q=80",
    category: "منزل ومطبخ",
    merchant: "Gulf Deals",
    storeName: "Home Deals KSA",
    merchantName: "Home Deals Trading",
    storeRating: 4.5,
    merchantCustomerRating: 4.5,
    merchantReviewCount: 892,
    merchantReliabilityScore: 89,
    merchantReliabilityLabel: "موثوق",
    merchantResponseRate: 91,
    merchantVerifiedSince: "2022",
    shippingInfo: "شحن منزلي خلال 3-5 أيام",
    returnPolicy: "إرجاع خلال 7 أيام للمنتجات غير المستخدمة",
    trustScore: 88,
    aiExplanation: "هذا المنتج مناسب للعائلة لأنه يجمع بين السعة الكبيرة والسعر الجيد. الخصم ليس الأعلى، لكنه خيار مستقر من متجر موثوق.",
    pros: ["سعة عائلية", "تنظيف سهل", "برامج طبخ جاهزة"],
    cons: ["حجمها كبير للمطابخ الصغيرة"],
    comparisonReason: "أفضل قيمة لمن يبحث عن سعة كبيرة بدل السعر الأرخص فقط.",
    affiliateUrl: "https://example.com/checkout/air-fryer-family?aff_id=demo",
    rating: 4.6,
    soldLastHour: 35,
    discountPercent: 18,
    availability: "LimitedAvailability",
  },
  {
    id: "skin-care-kit",
    title: "Glow Skin Care Kit",
    description: "مجموعة عناية يومية بالبشرة مع سيروم، مرطب، وغسول لطيف للاستخدام الصباحي والمسائي.",
    price: 59,
    originalPrice: 81,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=900&q=80",
    category: "جمال وعناية",
    merchant: "Beauty Hub",
    storeName: "Beauty Hub",
    merchantName: "Beauty Hub Retail",
    storeRating: 4.8,
    merchantCustomerRating: 4.9,
    merchantReviewCount: 2310,
    merchantReliabilityScore: 97,
    merchantReliabilityLabel: "موثوق جدًا",
    merchantResponseRate: 98,
    merchantVerifiedSince: "2019",
    shippingInfo: "شحن خلال 2-3 أيام",
    returnPolicy: "الإرجاع حسب سياسة منتجات العناية",
    trustScore: 96,
    aiExplanation: "الخيار الأفضل لمن يريد مجموعة متكاملة بدل شراء كل منتج منفصل. التقييم مرتفع والخصم جيد مقارنة بمنتجات العناية المشابهة.",
    pros: ["مجموعة متكاملة", "تقييم مرتفع", "سعر جيد للحزمة"],
    cons: ["قد لا يناسب كل أنواع البشرة"],
    comparisonReason: "أفضل حزمة من حيث السعر والتقييم وعدد المنتجات.",
    affiliateUrl: "https://example.com/checkout/skin-care-kit?aff_id=demo",
    rating: 4.9,
    soldLastHour: 51,
    discountPercent: 27,
    availability: "InStock",
  },
];
